version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
            - POSTGRES_PASSWORD=postgres_password 
    api:
        build:
            dockerfile: Dockerfile.dev
            context: .
        ports: 
            - "4000:4000"
        volumes: 
            - /app/node_modules
            - /app/dist
            - .:/app
        depends_on: 
            - postgres
        environment: 
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        stdin_open: true
    tests:
        build:
            dockerfile: Dockerfile.dev
            context: .
        volumes:
            - /app/node_modules
            - /app/dist
            - .:/app
        depends_on: 
            - postgres
        environment: 
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
        stdin_open: true
        command: ["npm", "run", "test"]